// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import <Foundation/Foundation.h>

/** (public) */
typedef NS_ENUM(NSInteger, SCKArTrackingState)
{
    SCKArTrackingStatePaused,
    SCKArTrackingStateStopped,
    SCKArTrackingStateTracking,
};
