// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import "SCKArFrame.h"
#import "SCKArWorldAlignment.h"
#import <Foundation/Foundation.h>
@protocol SCKArSessionObserver;


/**
 * (public)
 * Simple abstraction layer sitting on top of ARKit/ARCore: 
 * allows using AR related features (camera pose, plane detection, world alignment) easily
 */
@protocol SCKArSession

/** (public) */
- (void)startTracking;

/** (public) */
- (void)stopTracking;

/** (public) */
- (void)resetTracking;

/** (public) */
- (void)setWorldAlignment:(SCKArWorldAlignment)alignment;

/** (public) */
- (void)setPlaneDetection:(BOOL)detection;

/** (public) */
- (void)setDebugMode:(BOOL)debug;

/** (public) */
- (void)setLightEstimation:(BOOL)estimation;

/** (public) */
- (BOOL)isPlaneDetection;

/** (public) */
- (BOOL)isDebugMode;

/** (public) */
- (BOOL)isLightEstimation;

/** (public) */
- (SCKArWorldAlignment)getWorldAlignment;

/** (public) */
- (nullable SCKArFrame *)getLastFrame;

/** (public) */
- (nullable id<SCKArSessionObserver>)getArSessionObserver;

/** (public) */
- (void)setArSessionObserver:(nullable id<SCKArSessionObserver>)arSessionObserver;

@end
