// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import <Foundation/Foundation.h>

@interface SCKArEulerAngles : NSObject
- (nonnull instancetype)initWithPitch:(double)pitch
                                  yaw:(double)yaw
                                 roll:(double)roll;
+ (nonnull instancetype)arEulerAnglesWithPitch:(double)pitch
                                           yaw:(double)yaw
                                          roll:(double)roll;

@property (nonatomic, readonly) double pitch;

@property (nonatomic, readonly) double yaw;

@property (nonatomic, readonly) double roll;

@end
