// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import <Foundation/Foundation.h>

@interface SCKArAnchor : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                         transform:(nonnull NSArray<NSNumber *> *)transform;
+ (nonnull instancetype)arAnchorWithId:(nonnull NSString *)id
                             transform:(nonnull NSArray<NSNumber *> *)transform;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * transform;

@end
