// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import "SCKArAlignment.h"
#import "SCKArCenter.h"
#import "SCKArExtent.h"
#import "SCKArNode.h"
#import <Foundation/Foundation.h>

/** (public) */
@interface SCKArPlane : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                         alignment:(SCKArAlignment)alignment
                              node:(nonnull SCKArNode *)node
                            center:(nonnull SCKArCenter *)center
                            extent:(nonnull SCKArExtent *)extent;
+ (nonnull instancetype)arPlaneWithId:(nonnull NSString *)id
                            alignment:(SCKArAlignment)alignment
                                 node:(nonnull SCKArNode *)node
                               center:(nonnull SCKArCenter *)center
                               extent:(nonnull SCKArExtent *)extent;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly) SCKArAlignment alignment;

@property (nonatomic, readonly, nonnull) SCKArNode * node;

@property (nonatomic, readonly, nonnull) SCKArCenter * center;

@property (nonatomic, readonly, nonnull) SCKArExtent * extent;

@end
