// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import <Foundation/Foundation.h>

/** (public) */
@interface SCKArLight : NSObject
- (nonnull instancetype)initWithAmbientIntensity:(double)ambientIntensity
                         ambientColorTemperature:(double)ambientColorTemperature;
+ (nonnull instancetype)arLightWithAmbientIntensity:(double)ambientIntensity
                            ambientColorTemperature:(double)ambientColorTemperature;

@property (nonatomic, readonly) double ambientIntensity;

@property (nonatomic, readonly) double ambientColorTemperature;

@end
