// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ar.djinni

#import <Foundation/Foundation.h>

/** (public) */
@interface SCKArExtent : NSObject
- (nonnull instancetype)initWithX:(double)x
                                y:(double)y
                                z:(double)z;
+ (nonnull instancetype)arExtentWithX:(double)x
                                    y:(double)y
                                    z:(double)z;

@property (nonatomic, readonly) double x;

@property (nonatomic, readonly) double y;

@property (nonatomic, readonly) double z;

@end
