// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from threading.djinni

#import <Foundation/Foundation.h>
@class SCKExecutable;


/** internal - do not use */
@protocol SCKExecutorService

- (void)execute:(nullable SCKExecutable *)executable;

@end
