// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import <Foundation/Foundation.h>

/**
 * (public)
 * Represents the desired source type used to fetch the Measurements
 */
typedef NS_ENUM(NSInteger, SCKGeoSourceType)
{
    /** Represents device's built-in sensors (gyroscope, accelerometer, gps, magnetometer)  */
    SCKGeoSourceTypeRawSensors,
    /** Represents device's built-in sensors combined with Scape Vision Engine  */
    SCKGeoSourceTypeRawSensorsAndScapeVisionEngine,
};
