// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import "SCKLogLevel.h"
#import "SCKLogOutput.h"
#import <Foundation/Foundation.h>


@interface SCKLog : NSObject

+ (void)log:(SCKLogOutput)output
      level:(SCKLogLevel)level
    message:(nonnull NSString *)message;

+ (void)logverb:(nonnull NSString *)tag
            msg:(nonnull NSString *)msg;

+ (void)logdebug:(nonnull NSString *)tag
             msg:(nonnull NSString *)msg;

+ (void)loginfo:(nonnull NSString *)tag
            msg:(nonnull NSString *)msg;

+ (void)logwarn:(nonnull NSString *)tag
            msg:(nonnull NSString *)msg;

+ (void)logerrf:(nonnull NSString *)tag
            msg:(nonnull NSString *)msg;

@end
