// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#import <Foundation/Foundation.h>

/** (internal) */
typedef NS_ENUM(NSInteger, SCKLogOutput)
{
    SCKLogOutputConsole,
    SCKLogOutputOverlay,
};
