// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import "SCKLocationMeasurements.h"
#import "SCKMotionMeasurements.h"
#import "SCKScapeMeasurements.h"
#import <Foundation/Foundation.h>

/**
 * (public)
 * Raw measurements read from device's sensors (gyroscope, accelerometer, gps, magnetometer) and Scape Vision Engine.
 */
@interface SCKMeasurements : NSObject
- (nonnull instancetype)initWithDeviceLocationMeasurements:(nonnull SCKLocationMeasurements *)deviceLocationMeasurements
                                  deviceMotionMeasurements:(nonnull SCKMotionMeasurements *)deviceMotionMeasurements
                                         scapeMeasurements:(nonnull SCKScapeMeasurements *)scapeMeasurements
                                           cameraTransform:(nonnull NSArray<NSNumber *> *)cameraTransform;
+ (nonnull instancetype)measurementsWithDeviceLocationMeasurements:(nonnull SCKLocationMeasurements *)deviceLocationMeasurements
                                          deviceMotionMeasurements:(nonnull SCKMotionMeasurements *)deviceMotionMeasurements
                                                 scapeMeasurements:(nonnull SCKScapeMeasurements *)scapeMeasurements
                                                   cameraTransform:(nonnull NSArray<NSNumber *> *)cameraTransform;

/** Device's location-related measurements */
@property (nonatomic, readonly, nonnull) SCKLocationMeasurements * deviceLocationMeasurements;

/** Device's motion-related measurements */
@property (nonatomic, readonly, nonnull) SCKMotionMeasurements * deviceMotionMeasurements;

/** Scape-related measurements */
@property (nonatomic, readonly, nonnull) SCKScapeMeasurements * scapeMeasurements;

/** Camera transform matrix4x4 representing the current translation and rotation of the device computed from ARKit/ARCore */
@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * cameraTransform;

@end
