// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from motion.djinni

#import <Foundation/Foundation.h>

/**
 * (public)
 * The accelerometer, gyroscope and magnetometer measurements
 */
@interface SCKMotionMeasurements : NSObject
- (nonnull instancetype)initWithAcceleration:(nullable NSArray<NSNumber *> *)acceleration
                       accelerationTimeStamp:(nullable NSNumber *)accelerationTimeStamp
                            userAcceleration:(nullable NSArray<NSNumber *> *)userAcceleration
                                        gyro:(nullable NSArray<NSNumber *> *)gyro
                               gyroTimestamp:(nullable NSNumber *)gyroTimestamp
                                magnetometer:(nullable NSArray<NSNumber *> *)magnetometer
                       magnetometerTimestamp:(nullable NSNumber *)magnetometerTimestamp
                                     gravity:(nullable NSArray<NSNumber *> *)gravity
                                    attitude:(nullable NSArray<NSNumber *> *)attitude;
+ (nonnull instancetype)motionMeasurementsWithAcceleration:(nullable NSArray<NSNumber *> *)acceleration
                                     accelerationTimeStamp:(nullable NSNumber *)accelerationTimeStamp
                                          userAcceleration:(nullable NSArray<NSNumber *> *)userAcceleration
                                                      gyro:(nullable NSArray<NSNumber *> *)gyro
                                             gyroTimestamp:(nullable NSNumber *)gyroTimestamp
                                              magnetometer:(nullable NSArray<NSNumber *> *)magnetometer
                                     magnetometerTimestamp:(nullable NSNumber *)magnetometerTimestamp
                                                   gravity:(nullable NSArray<NSNumber *> *)gravity
                                                  attitude:(nullable NSArray<NSNumber *> *)attitude;

/** A data sample from the device's three accelerometers. */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * acceleration;

@property (nonatomic, readonly, nullable) NSNumber * accelerationTimeStamp;

/** The acceleration that the user is giving to the device. */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * userAcceleration;

/** A single measurement of the device’s rotation rate. */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * gyro;

@property (nonatomic, readonly, nullable) NSNumber * gyroTimestamp;

/** Measurements of the Earth's magnetic field relative to the device. */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * magnetometer;

@property (nonatomic, readonly, nullable) NSNumber * magnetometerTimestamp;

/** The gravity acceleration vector expressed in the device's reference frame. */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * gravity;

/** The attitude of the device */
@property (nonatomic, readonly, nullable) NSArray<NSNumber *> * attitude;

@end
