// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import "SCKLocationMeasurements.h"
#import "SCKMotionMeasurements.h"
#import "SCKScapeMeasurements.h"
#import "SCKScapeSessionState.h"
#import <Foundation/Foundation.h>
@class SCKScapeSession;


/**
 * (public)
 * Observer for all ScapeSession related callbacks
 */
@protocol SCKScapeSessionObserver

/** Called whenever any kind of error happens during the session lifetime */
- (void)onScapeSessionError:(nullable SCKScapeSession *)session
                      state:(SCKScapeSessionState)state
                    message:(nonnull NSString *)message;

/** Called when new device's location sensors measurements are available */
- (void)onDeviceLocationMeasurementsUpdated:(nullable SCKScapeSession *)session
                               measurements:(nullable SCKLocationMeasurements *)measurements;

/** Called when new device's motion sensors measurements are available */
- (void)onDeviceMotionMeasurementsUpdated:(nullable SCKScapeSession *)session
                             measurements:(nullable SCKMotionMeasurements *)measurements;

/** Called when new scape measurements are available */
- (void)onScapeMeasurementsUpdated:(nullable SCKScapeSession *)session
                      measurements:(nullable SCKScapeMeasurements *)measurements;

/** Called when a new camera transform is available */
- (void)onCameraTransformUpdated:(nullable SCKScapeSession *)session
                       transform:(nullable NSArray<NSNumber *> *)transform;

@end
