// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scape.djinni

#import <Foundation/Foundation.h>

/**
 * (public)
 * Scape orientation representing the current translation and rotation of the device (in North East Down reference frame)
 */
@interface SCKScapeOrientation : NSObject
- (nonnull instancetype)initWithX:(double)x
                                y:(double)y
                                z:(double)z
                                w:(double)w;
+ (nonnull instancetype)scapeOrientationWithX:(double)x
                                            y:(double)y
                                            z:(double)z
                                            w:(double)w;

@property (nonatomic, readonly) double x;

@property (nonatomic, readonly) double y;

@property (nonatomic, readonly) double z;

@property (nonatomic, readonly) double w;

@end
