// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from video.djinni

#import <Foundation/Foundation.h>


/** public interface */
@protocol SCKVideoFrame

/** public  */
- (int64_t)getData;

/** public  */
- (int64_t)getSize;

/** public  */
- (int32_t)getWidth;

/** public  */
- (int32_t)getHeight;

/** public  */
- (double)getTimestamp;

/** public  */
- (void)setData:(int64_t)data;

/** public  */
- (void)setSize:(int64_t)size;

/** public  */
- (void)setWidth:(int32_t)width;

/** public  */
- (void)setHeight:(int32_t)height;

/** public  */
- (void)setTimestamp:(double)timestamp;

@end
